name: textlint

on:
  push:
    paths:
      - 'README.md'

jobs:
  textlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
      - uses: actions/checkout@v4

      - name: cache-node-modules
        uses: pat-s/always-upload-cache@v2.1.3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-

      - name: Install textlint
        run: npm install --save-dev textlint @textlint-rule/textlint-rule-preset-google

      - name: Install dependent module
        run: npm install

      - name: Execute textlint for README.md
        run: npx textlint -f checkstyle README.md
